[package]
name = "shard_lock"
version = "0.0.1"
authors = ["nkconnor <nicholas.k.connor@gmail.com>"]
edition = "2018"


[dependencies]
parking_lot = "0.11"

[dev-dependencies]
criterion = "0.3"
dashmap = "3.11.10"
uuid = { version = "0.8", features=["v4"] }
flurry = "0.3.0"


[[bench]]
name = "simple"
harness = false
