[package]
name = "sharded"
version = "0.0.1"
authors = ["nkconnor <nicholas.k.connor@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Safe, fast, and obvious concurrent collections"
repository = "https://github.com/nkconnor/sharded"
documentation = "https://docs.rs/sharded"
readme = "README.md"

[dependencies]
parking_lot = {version="0.11", optional=true}
ahash = {version ="0.4.4", optional = true}
hashbrown = {version = "0.8.2", optional = true}
crossbeam = {version="0.7.1", optional = true}

[features]
lock-crossbeam = ["crossbeam"]
lock-parking-lot = ["parking_lot"]
hash-ahash = ["ahash"]
map-hashbrown = ["hashbrown"]

# 3rd-party = ["parking_lot", "ahash", "hashbrown"]
